#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────────────────
# OAuth client wizard — IaC 化が原理的に不可能な Console 手動ステップの案内役。
#
# 守備範囲（#4722 prototype）:
#   Google Auth Platform の Branding / Audience（プロジェクトに 1 回）
#   → Clients の Desktop app 作成 / secret 発行 / Download JSON（チャンネルごと）
#   → `yt-doctor --fix-client-secrets` で auth/ へ配置 → doctor 再診断。
# GCP 層（project / billing / API / IAM）は上流 infra/terraform/gcp/ が正で、
# ここでは触らない。OAuth token の取得（ブラウザ認証）も範囲外。
#
# 実行: チャンネルリポジトリのルートで
#   bash .claude/skills/setup/references/oauth-client-wizard.sh
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

CHANNEL_DIR="${CHANNEL_DIR:-$PWD}"
DEST="$CHANNEL_DIR/auth/client_secrets.json"
META_JSON="$CHANNEL_DIR/config/channel/meta.json"

CHANNEL_NAME=""
if [[ -f "$META_JSON" ]] && command -v python3 >/dev/null 2>&1; then
  CHANNEL_NAME=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["channel"].get("name",""))' "$META_JSON" 2>/dev/null || true)
fi

PROJECT_ID="${GOOGLE_CLOUD_PROJECT:-}"
if [[ -z "$PROJECT_ID" ]] && command -v gcloud >/dev/null 2>&1; then
  PROJECT_ID=$(gcloud config get-value project 2>/dev/null || true)
fi

CONSOLE="https://console.cloud.google.com"

banner "YouTube OAuth client セットアップ（Console 手動ステップ）"

# ── Stage 1: 前提確認 ─────────────────────────────────────────────────────
stage "前提確認"
say "この wizard は Console でしかできない Google Auth Platform の設定を案内し、"
say "ダウンロードした client secret を auth/ へ配置して doctor で確認します。"
printf '\n'
note "チャンネルディレクトリ: $CHANNEL_DIR"
note "配置先:                 $DEST"
if [[ -f "$DEST" ]]; then
  printf '\n'
  warn "$DEST は既に存在します。再発行する場合は先に退避してください。"
  say  "確認だけ行うなら: uv run yt-doctor --json"
  exit 0
fi
if [[ -z "$CHANNEL_NAME" ]]; then
  ask CHANNEL_NAME "チャンネル名（config/channel/meta.json から読めませんでした。推奨名に使います）:"
else
  note "チャンネル名:           $CHANNEL_NAME"
fi
if [[ -z "$PROJECT_ID" ]]; then
  warn "GCP project ID を GOOGLE_CLOUD_PROJECT / gcloud config から解決できませんでした。"
  ask PROJECT_ID "GCP project ID（ADR-0010 の単一プロジェクト）:"
else
  note "GCP project:            $PROJECT_ID"
fi
printf '\n'
say "Branding / Audience は GCP プロジェクトに 1 つの同意画面の設定です（チャンネルごとではありません）。"
FIRST_IN_PROJECT=0
if confirm "このプロジェクトで Branding / Audience を設定するのは初めてですか？"; then
  FIRST_IN_PROJECT=1
else
  TOTAL_STAGES=4
  note "Branding / Audience の 2 stage を飛ばします。"
fi
pause

# ── Stage 2: Branding（プロジェクトに 1 回） ──────────────────────────────
if (( FIRST_IN_PROJECT )); then
  stage "Google Auth Platform › Branding"
  open_url "$CONSOLE/auth/branding?project=$PROJECT_ID"
  note "開けない場合: $CONSOLE/apis/credentials?project=$PROJECT_ID → 左メニュー「Google Auth Platform」→「Branding」"
  step "アプリ名: ${BOLD}${CHANNEL_NAME} YouTube Automation${RESET}"
  note "  同意画面はプロジェクトに 1 つ。複数チャンネルで共用するならチャンネル名を外した名前でもよい"
  step "ユーザーサポートメール: 自分の Google アカウント"
  step "デベロッパーの連絡先情報: 同じアカウント"
  step "「保存」"
  pause "保存できたら Enter"
fi

# ── Stage 3: Audience（プロジェクトに 1 回） ──────────────────────────────
if (( FIRST_IN_PROJECT )); then
  stage "Google Auth Platform › Audience"
  open_url "$CONSOLE/auth/audience?project=$PROJECT_ID"
  step "User type: ${BOLD}External${RESET}"
  step "Publishing status: ${BOLD}In production${RESET} に切り替える（「Publish app」）"
  note "  Testing のままだと refresh token が 7 日で失効し、無人運用（token_streaming）が週次で止まる（#4716 / #4717）"
  note "  verification は申請しない。初回認証で「このアプリは Google で確認されていません」が出たら"
  note "  「詳細」→「（アプリ名）に移動（安全ではないページ）」で続行する運用"
  printf '\n'
  if ! confirm "In production に切り替えましたか？"; then
    warn "Testing のまま進めます。Test users にログインする Google アカウントを追加してください"
    step "「Test users」→「Add users」→ OAuth 認証でログインするアカウントを追加 → 保存"
    note "  未追加だと初回認証が 403 access_denied で止まります"
    pause "追加できたら Enter"
  fi
fi

# ── Stage 4: Clients（チャンネルごと） ───────────────────────────────────
stage "Google Auth Platform › Clients — Desktop app 作成"
open_url "$CONSOLE/auth/clients?project=$PROJECT_ID"
step "「Create client」"
step "Application type: ${BOLD}Desktop app${RESET}"
CLIENT_NAME_DEFAULT="${CHANNEL_NAME} Desktop Client"
step "Name: ${BOLD}${CLIENT_NAME_DEFAULT}${RESET}"
step "「Create」"
pause "作成できたら Enter"

# ── Stage 5: secret 発行 → Download JSON → auth/ へ配置 ──────────────────
stage "Client secret の発行と配置"
step "作成した client を開く → 「Client secrets」→「Add secret」"
step "「Download JSON」→ ~/Downloads に保存（ファイル名は client_secret_*.json）"
note "  新 UI は作成直後のポップアップの secret 再表示に依存しない。見失ったら Add secret でもう一度発行する"
pause "ダウンロードできたら Enter"
printf '\n'
_dl=()
while IFS= read -r _f; do [[ -n "$_f" ]] && _dl+=("$_f"); done < <(ls -t "$HOME"/Downloads/client_secret*.json 2>/dev/null || true)
if (( ${#_dl[@]} == 0 )); then
  warn "~/Downloads に client_secret*.json が見つかりません。"
  pause "保存し直したら Enter"
else
  say "Downloads の候補（新しい順）:"
  for f in "${_dl[@]}"; do note "  - $f"; done
fi
if confirm "uv run yt-doctor --fix-client-secrets を実行して $DEST へ移動しますか？"; then
  if (cd "$CHANNEL_DIR" && uv run yt-doctor --fix-client-secrets); then
    printf '  %s✓ 配置%s %s\n' "$GREEN" "$RESET" "$DEST"
  else
    warn "配置に失敗しました。上のメッセージを確認し、解決後にもう一度 wizard を実行してください"
    SKIPPED+=("auth/client_secrets.json の配置（uv run yt-doctor --fix-client-secrets）")
  fi
else
  SKIPPED+=("auth/client_secrets.json の配置（uv run yt-doctor --fix-client-secrets）")
fi
pause

# ── Stage 6: doctor で確認 ────────────────────────────────────────────────
stage "yt-doctor で確認"
say "client_secrets check が ok になるか確認します。"
_status=$(cd "$CHANNEL_DIR" && uv run yt-doctor --json 2>/dev/null \
  | python3 -c 'import json,sys; d=json.load(sys.stdin); print(next((c["status"] for c in d.get("checks",[]) if c.get("id")=="client_secrets"),"unknown"))' 2>/dev/null || echo unknown)
if [[ "$_status" == "ok" ]]; then
  printf '  %s✓ client_secrets: ok%s\n' "$GREEN" "$RESET"
else
  warn "client_secrets: $_status"
  SKIPPED+=("client_secrets check を ok にする（uv run yt-doctor --json で詳細を確認）")
fi
printf '\n'
note "次のステップ（この wizard の範囲外）: /setup --tool の続きで oauth_token を取得（ブラウザ認証）"
pause

finish
